name: flutter_onboarding_ui
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: CM Sans Serif
      fonts:
        - asset: assets/fonts/cm_sans_serif_2012.ttf

    - family: KPMG_Light
      fonts:
        - asset: assets/fonts/KPMG_Light.ttf
        - asset: assets/fonts/KPMG_Light_Bold.ttf
          weight: 700

    - family: Uni
      fonts:
        - asset: assets/fonts/Uni.ttf
        - asset: assets/fonts/Uni_Bold.ttf
          weight: 700
